version: '3.8'

networks:
  demos:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.27
    volumes:
      - ./data/database-init.sql:/docker-entrypoint-initdb.d/database-init.sql
#    ports:
#      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - demos

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - DB_HOST=mysql
    networks:
      - demos
    depends_on:
      - mysql